### ISSUE TITLE
On IOS we get error when the application starts

### ISSUE THREAD

**Issue by OroviaTraining** [cedricgabrang/MauiFirebaseDemo#1]
[0:] An error occurred: 'Object reference not set to an instance of an object.'. Callstack: '   at Plugin.Firebase.CloudMessaging.FirebaseCloudMessagingImplementation.RegisterForRemoteNotifications()
   at Plugin.Firebase.CloudMessaging.FirebaseCloudMessagingImplementation.Initialize()
   at Plugin.Firebase.iOS.CrossFirebase.Initialize(UIApplication app, NSDictionary options, CrossFirebaseSettings settings, Options firebaseOptions, String name)
   at MauiFirebaseDemo.MauiProgram.<>c.<RegisterFirebaseServices>b__1_3(UIApplication app, NSDictionary launchOptions) in C:\SourceCode\PlayGround\MauiFirebaseDemo\MauiProgram.cs:line 36
   at Microsoft.Maui.MauiUIApplicationDelegate.<>c__DisplayClass6_0.<FinishedLaunching>b__0(FinishedLaunching del)
   at Microsoft.Maui.LifecycleEvents.LifecycleEventServiceExtensions.InvokeLifecycleEvents[FinishedLaunching](IServiceProvider services, Action`1 action)
   at Microsoft.Maui.MauiUIApplicationDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at MauiFirebaseDemo.Program.Main(String[] args) in C:\SourceCode\PlayGround\MauiFirebaseDemo\Platforms\iOS\Program.cs:line 13
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)'
The app has been terminated.

**Comment by glihm** [comment]
Yup, we have the exact same issue. Importing the source code of the library, the field causing this is the `Messaging.SharedInstance` field which is null. This can be found [here](https://github.com/TobiasBuchholz/Plugin.Firebase/blob/527bec4d2bdfe07a4a595f3d15597c0d91662dde/src/iOS/CloudMessaging/FirebaseCloudMessagingImplementation.cs#L29). This where the exception is raised.

Seems that also this field is `readonly`, so unable to initialize it by hand for testing purposes. The value is retrieved like this:
`return Runtime.GetNSObject<Messaging>(ApiDefinition.Messaging.NativeHandle_objc_msgSend(class_ptr, Selector.GetHandle("messaging")));` from Objective-C code directly.

Any idea @cedricgabrang ?

**Comment by harima34** [comment]
Hi there, i got the same issue also, did you found how to solve this problem ?
